version: '1'
services:
  dnscrypt-proxy:
    restart: unless-stopped
    image: xtr0py/dnscrypt-proxy-2-docker
    container_name: dnscrypt-proxy-2-docker
    ports:
      - "53:53/udp"
    #volumes:
    #  - ./config:/config
